name: ST-Warp
main: net.starly.warp.WarpMain
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

version: 1.0
api-version: 1.16

commands:
  warp:
    aliases: [워프]
  spawn:
    aliases: [스폰,넴주,tmvhs]
  setspawn:
    aliases: [셋스폰,스폰설정]