name: NK-Warp
main: com.github.nicks.warp.Main
author: idkNicks
website: https://github.com/idkNicks

version: 1.0
api-version: 1.19


commands:
  warp:
    aliases: [워프]
  spawn:
    aliases: [스폰,넴주,tmvhs]
  setspawn:
    aliases: [셋스폰,스폰설정]